#!/usr/bin/env bash
set -e 
set -o pipefail

cd "$(dirname "$0")"
echo  -e "\033[32m \nActivate Django environment"
source ENV/bin/activate

# Events
echo -e "\033[32m \nProcess EVENTS ... \033[0m"
./manage.py runscript cn-events --traceback || exit

# Participants
echo -e "\033[32m \nProcess PARTICIPANTS ... \033[0m"
./manage.py runscript cn-participants --traceback || exit

# Talks
echo -e "\033[32m \nProcess TALKS ... \033[0m"
./manage.py runscript cn-talks --traceback || exit

# Keyword Extraction
echo -e "\033[32m Extract KEYWORDS from TALKS ... \033[0m"
./manage.py runscript cn-keywords --traceback || exit

# Bookmarks
echo -e "\033[32m \nProcess BOOKMARKS ... \033[0m"
./manage.py runscript cn-bookmarks --traceback || exit

# Old papers from bookmarks
echo -e "\033[32m \nProcess OLD PAPERS ... \033[0m"
./manage.py runscript cn-old-papers --traceback || exit

# User-Neighbor Similarity
echo -e "\033[32m \nProcess USER-NEIGHBOR SIM ... \033[0m"
./manage.py runscript cn-sim-user-neighbor --traceback || exit

# User-Talk Similarity
echo -e "\033[32m \nProcess USER-TALK SIM ... \033[0m"
./manage.py runscript cn-sim-user-talk --traceback || exit


echo -e "\033[32m \nFinished Conference Navigator preparation successfully \033[0m"