#!/usr/bin/env bash
set -e 
set -o pipefail

cd "$(dirname "$0")"

echo  -e "\033[32m \nUPDATE FROM GIT REPOSITORY \033[0m"
sudo -u cecidisi git reset --hard
sudo -u cecidisi git pull
sudo -u cecidisi git submodule update --init --recursive

echo  -e "\033[32m \nRunning updates ... \033[0m"
./scripts/run_updates
