#!/usr/bin/env bash
source ENV/bin/activate

echo  -e "\033[32m \n(1/5) Install requirements with pip \033[0m"
pip install -r requirements.txt

echo  -e "\033[32m \n(2/5) Build static files with Webpack \033[0m"
sudo -u cecidisi npm run build

echo  -e "\033[32m \n(3/5) Run Django collectstatic \033[0m"
./manage.py collectstatic --no-input

echo  -e "\033[32m \n(4/5) Set \"DEBUG = False\" in settings.py \033[0m"
python scripts/settings-no-debug.py

echo -e "\033[32m \n(5/5) RESTARTING SERVER ... \033[0m"
systemctl restart httpd

echo -e "\033[32m \nREADY!! \033[0m"
echo -e "\033[32m \tTo update Conference Navigator: Run \033[0m sudo ./prepare_cn \033[0m"
echo -e "\033[32m \tTo setup UPMC: Run \033[0m sudo ./setup_upmc \033[0m"