#!/usr/bin/env bash
set -e 
set -o pipefail

# cd to project root
cd "$(dirname "$0")/.."


echo -e "\033[32m \n(1/4) CREATE DATABASE IF NOT EXIST \033[0m"
DBNAME=upmc
USER=cecidisi
PSWD=asdf

echo "Please enter root user MySQL password:"
read -s rootpasswd

mysql -uroot -p${rootpasswd} -e "CREATE DATABASE IF NOT EXISTS ${DBNAME} /*\!40100 DEFAULT CHARACTER SET utf8 */;" || exit
mysql -uroot -p${rootpasswd} -e "CREATE USER IF NOT EXISTS ${USER}@localhost IDENTIFIED BY '${PSWD}';" || exit
mysql -uroot -p${rootpasswd} -e "GRANT ALL ON ${DBNAME}.* to '${USER}'@'localhost' IDENTIFIED BY '${PSWD}';" || exit
# mysql -u${USER} -p${PSWD} -e "FLUSH PRIVILEGES;" || exit

# activate virtualenv
source ENV/bin/activate

echo  -e "\033[32m \n(2/4) MAKE MIGRATIONS TO DB \033[0m"
./manage.py makemigrations upmc_urank
./manage.py migrate --database upmcdb upmc_urank


echo  -e "\033[32m \n(3/4) FETCH PUBMED DOCUMENTS FROM ENTREZ API \033[0m"
./manage.py runscript --traceback upmc-entrez || exit

echo  -e "\033[32m \n(4/4) EXTRACT KEYWORDS AND PHRASES \033[0m"
./manage.py runscript --traceback kwext || exit

echo  -e "\033[32m \nREADY!! \033[0m"

